### ISSUE TITLE
Key ^ does not work

### ISSUE THREAD

**Issue by marvinrabe** [jgosmann/KE-complex_modifications#10]
The ^ Key (next to 1) does not work when "Neo2 mod 3 and 4 keys (Apple keyboard)" is enabled.

The problem does not exist on the "Window keyboard" variant.

**Comment by jgosmann** [comment]
It is working for me and the Karabiner modifications should not affect it ... 🤔

**Comment by marvinrabe** [comment]
Found the problem: My Apple Keyboard was not configured to be an Apple keyboard… 🤷‍♂️

In Settings -> Keyboard -> Change Keyboard Type I was able to change the type.

**Comment by MilkaLichtblau** [comment]
I'm having the same issue being on a US keyboard layout (meaning that ~` is not working), but I can't change the Type to "Apple keyboard", because that option seems to not exist. Can we reopen this issue, or shall I create a new one?

**Comment by jgosmann** [comment]
What kind of keyboard are you using? Is it the internal keyboard of a Macbook or is it an external keyboard? If it is an external keyboard, is it an Apple keyboard?

**Comment by MilkaLichtblau** [comment]
internal MacbookPro 2017 (the one with the touch bar) keyboard with US layout. 
When I disable the aforementioned rule, the problem goes away.

**Comment by jgosmann** [comment]
The rule was written for a German/ISO style keyboard, but the US keyboard is ANSI style. Certain keycodes might be different like in the Windows keyboard variant. Can you test that one? It might already fully work, otherwise it might be necessary to create a third variant.

**Comment by marvinrabe** [comment]
@MilkaLichtblau One of my keyboards behaves differently than my main keyboard. I fixed the key issue by swapping the keys in Karabiner:

![bildschirmfoto 2019-02-08 um 10 14 35](https://user-images.githubusercontent.com/515860/52468916-60248c80-2b8a-11e9-8e29-a3a3a5fa7256.png)

Maybe this helps.

**Comment by MilkaLichtblau** [comment]
@jgosmann that seemed to fix the issue for now, thank you. 
@marvinrabe Thank you for the suggestion, I'm however a bit hesitant to do that, because I'm a total newbie to Neo and I still need the other keyboard and I also want to allow other people to use my computer from time to time. So I don't want to switch key functionality globally but rather for the Neo layout only, if this is possible.
Is there any tutorial or anything on how to write such rules? I also noticed that my mode3 keys for Neo are both on the left side (Capslock and left side option), which does not allow convenient usage of the left hand keys. So I thought of modifying the rule for Apple for the mode3 keys and trying to fix that "key-left-of-1" issue at the same time.

**Comment by MilkaLichtblau** [comment]
hm, I just figured out, that the key left of 1 is not working properly also with the Windows-Layout. So apparently the problem is, that the key does not switch its functionality with the different keyboard layouts. So when I use the Apple rule, it would always stay a Neo2 key (mode4) and when I used the Windows rule, it would always stay a QWERTZ key (<), no matter what Layout was enabled.

**Comment by jgosmann** [comment]
The Karabiner rules are independent of the active current layout and I'm not aware of any way to change that. As a workaround you can create multiple profiles in Karabiner (e.g. one with the Neo2 rules and one without) and switch between them quickly via the menu bar icon. Still means you have to change two things (the keyboard layout and the Karabiner profile), but I am not aware of any better way at the moment.
